### ISSUE TITLE
open orderbook documentation

### ISSUE THREAD

**Issue by benjiqq** [raydium-io/raydium-amm#10]
i am trying to understand the details of orderbook. there is a flag ```enable_orderbook``` but not sure how it set or used. when is the orderbook active?

https://github.com/raydium-io/raydium-amm/blob/master/program/src/processor.rs#L1287

**Comment by benjiqq** [comment]
this isnt very clear how this precisely operates
https://docs.raydium.io/raydium/updates/integration-with-openbook
https://docs.raydium.io/raydium/pool-creation/creating-a-standard-amm-pool

From FAQ

```
OpenBook market IDs allow Raydium to market make with idle liquidity at a later stage - when your pool has bootstrapped enough liquidity - on the OpenBook CLOB. 

The 3-4 SOL fees are not paid to either Raydium or Openbook but are consumed during the market creation process to initialize accounts. 
Hence, these fees can not be refunded if you wrongly set up your parameters. 

We recommend that you be extremely careful during this process. Refer to the how-to guide and reach out on [discord](https://discord.com/invite/6EvFwvCfpx) if you have any doubts.
```

**Comment by RainRaydium** [comment]
Determined by the `status` saved in `AmmInfo`, currently controlled by the admin.
You can refer to [https://github.com/raydium-io/raydium-amm/blob/master/program/src/state.rs#L296](url)
