### ISSUE TITLE
bug: change of arguments

### ISSUE THREAD

**Issue by benjiqq** [raydium-io/raydium-amm#12]
this line and other places where number of arguments are dynamic causes bugs, solscan has it wrong to.
https://github.com/raydium-io/raydium-amm/blob/master/program/src/processor.rs#L1585

workaround example checking number of arguments

```
let mut index = SERUM_MARKET_INDEX as usize;
    if ray_accs.len() == 17 {
        index -= 1;
    } 
```

**Comment by RainRaydium** [comment]
There is nothing wrong with here, because the variable `input_account_len` is assigned at the beginning of the function.

**Comment by RainRaydium** [comment]
> this line and other places where number of arguments are dynamic causes bugs, solscan has it wrong to. https://github.com/raydium-io/raydium-amm/blob/master/program/src/processor.rs#L1585
> 
> workaround example checking number of arguments
> 
> ```
> let mut index = SERUM_MARKET_INDEX as usize;
>     if ray_accs.len() == 17 {
>         index -= 1;
>     } 
> ```

There is nothing wrong with here, because the variable `input_account_len` is assigned at the beginning of the function.

**Comment by RainRaydium** [comment]
No problem, close.
