### ISSUE TITLE
deploy program is error

### ISSUE THREAD

**Issue by lijuchuan** [raydium-io/raydium-amm#19]
i build program localnet

Error: ELF error: ELF error: Multiple or no text sections, consider removing llc option: -function-sections

**Comment by lllanlll** [comment]
solana program deploy fail
Error: ELF error: ELF error: Multiple or no text sections, consider removing llc option: -function-sections

**Comment by beautybliss-toml** [comment]
I got error.
Error: ELF error: ELF error: Multiple or no text sections, consider removing llc option: -function-sections

**Comment by johnny-yue** [comment]
> i build program localnet
> 
> Error: ELF error: ELF error: Multiple or no text sections, consider removing llc option: -function-sections

try run this, and then clean, build, and deploy again.
solana-install init 1.16.27
