### ISSUE TITLE
Error 0x2e OrderAtSlotIsPlace

### ISSUE THREAD

**Issue by bachkimn** [raydium-io/raydium-amm#2]
Hi,
I encounter an error, with code 0x2e (OrderAtSlotIsPlaced) when send transaction to remove liquid from a LP.
 I am unable to locate where the error comes from as there is nowhere in the raydium-amm code base produce this error.
Please let me know what is wrong here?
Thanks
![Capture](https://github.com/raydium-io/raydium-amm/assets/47156834/90349d19-70a7-43ad-8bb0-d2e883e27ea9)

**Comment by RainRaydium** [comment]
Early version, there is nothing wrong with this problem.
