### ISSUE TITLE
Bug decode StateData at AmmInfo

### ISSUE THREAD

**Issue by tomarock** [raydium-io/raydium-amm#23]
The swap_pc_in_amount value is false and all fields that follow.
Operating System: Ubuntu 22.04.5 LTS              
Kernel: Linux 6.8.0-45-generic
Architecture: x86-64
rustc 1.81.0 (eeb90cda1 2024-09-04)

**Comment by RainRaydium** [comment]
> The swap_pc_in_amount value is false and all fields that follow. Operating System: Ubuntu 22.04.5 LTS Kernel: Linux 6.8.0-45-generic Architecture: x86-64 rustc 1.81.0 (eeb90cda1 2024-09-04)

OK, thanks, we will test to check.

**Comment by RainRaydium** [comment]
Hi, this issue has been solved in [https://github.com/raydium-io/raydium-amm/pull/24](url).
Thanks for your info.
