### ISSUE TITLE
Decoding transaction instruction in RUST 

### ISSUE THREAD

**Issue by iamnotstatic** [raydium-io/raydium-amm#9]
I'm working on listening for events on Raydium v4 AMM program and have figured out most of what I need. However, I'm currently stuck on decoding Raydium transaction instructions. Has anyone done something similar or know a good approach for this? Any help would be greatly appreciated.

**Comment by RainRaydium** [comment]
I don't know if it's available for now, maybe you need to search on browser, and the source code is open source now, or you can try to parse it yourself.
